spring:
  application:
    name: BankCardService

  datasource:
    url: jdbc:mysql://localhost:3306/CardService
    username: CardServiceUser
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9090